name: Start Dev Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start server.js in background
        run: |
          node server.js 5173 > server.log 2>&1 &
          echo $! > server.pid

      - name: Wait for server to be ready
        run: npx --yes wait-on https://roman-dotsenko.github.io/StaticAsorikWebsite/

      - name: Show server logs (always)
        if: always()
        run: |
          echo '--- server.log ---'
          test -f server.log && tail -n +1 server.log || echo 'No log file'

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
          fi
